/*
https://mocki.io/v1/af96501c-cf82-4c55-bc0f-39253de660f4
API was generated by mocki.io
*/

const data = [
  {
    id: 1,
    title: 'Cover',
    date: '05/21/21',
    color: '#925DDB'
  },
  {
    id: 2,
    title: 'Section 1',
    date: '05/21/21',
    color: '#89CC79'
  },
  {
    id: 3,
    title: 'Section 2',
    date: '05/21/21',
    color: '#76AED3'
  },
  {
    id: 4,
    title: 'Section 3',
    date: '05/21/21',
    color: '#EC37A6'
  },
  {
    id: 5,
    title: 'Section 4',
    date: '05/21/21',
    color: '#FBB64E'
  },
  {
    id: 6,
    title: 'Section 5',
    date: '05/21/21',
    color: '#276ED6'
  },
  {
    id: 7,
    title: 'Section 6',
    date: '05/21/21',
    color: '#F8723E'
  },
  {
    id: 8,
    title: 'Section 7',
    date: '05/21/21',
    color: '#8DD8B0'
  }
];

export default data;
